/**
 * ---------------------------------------
 * This demo was created using amCharts 5.
 * 
 * For more information visit:
 * https://www.amcharts.com/
 * 
 * Documentation is available at:
 * https://www.amcharts.com/docs/v5/
 * ---------------------------------------
 */

// Colors
var colors = {
  D: am5.color(0x244999),
  R: am5.color(0xd22532),
  N: am5.color(0x999999)
}

// Data
var data = [
	{ id: "0200", state: "AK", statename: "Alaska", party: "D" },
	{ id: "0101", state: "AL", statename: "Alabama", party: "R" },
	{ id: "0102", state: "AL", statename: "Alabama", party: "R" },
	{ id: "0103", state: "AL", statename: "Alabama", party: "R" },
	{ id: "0104", state: "AL", statename: "Alabama", party: "R" },
	{ id: "0105", state: "AL", statename: "Alabama", party: "R" },
	{ id: "0106", state: "AL", statename: "Alabama", party: "R" },
	{ id: "0107", state: "AL", statename: "Alabama", party: "D" },
	{ id: "0501", state: "AR", statename: "Arkansas", party: "R" },
	{ id: "0502", state: "AR", statename: "Arkansas", party: "R" },
	{ id: "0503", state: "AR", statename: "Arkansas", party: "R" },
	{ id: "0504", state: "AR", statename: "Arkansas", party: "R" },
	{ id: "0401", state: "AZ", statename: "Arizona", party: "R" },
	{ id: "0402", state: "AZ", statename: "Arizona", party: "D" },
	{ id: "0403", state: "AZ", statename: "Arizona", party: "D" },
	{ id: "0404", state: "AZ", statename: "Arizona", party: "D" },
	{ id: "0405", state: "AZ", statename: "Arizona", party: "R" },
	{ id: "0406", state: "AZ", statename: "Arizona", party: "D" },
	{ id: "0407", state: "AZ", statename: "Arizona", party: "D" },
	{ id: "0408", state: "AZ", statename: "Arizona", party: "R" },
	{ id: "0409", state: "AZ", statename: "Arizona", party: "R" },
	{ id: "0601", state: "CA", statename: "California", party: "R" },
	{ id: "0602", state: "CA", statename: "California", party: "D" },
	{ id: "0603", state: "CA", statename: "California", party: "N" },
	{ id: "0604", state: "CA", statename: "California", party: "D" },
	{ id: "0605", state: "CA", statename: "California", party: "R" },
	{ id: "0606", state: "CA", statename: "California", party: "D" },
	{ id: "0607", state: "CA", statename: "California", party: "D" },
	{ id: "0608", state: "CA", statename: "California", party: "D" },
	{ id: "0609", state: "CA", statename: "California", party: "D" },
	{ id: "0610", state: "CA", statename: "California", party: "D" },
	{ id: "0611", state: "CA", statename: "California", party: "D" },
	{ id: "0612", state: "CA", statename: "California", party: "D" },
	{ id: "0613", state: "CA", statename: "California", party: "N" },
	{ id: "0614", state: "CA", statename: "California", party: "D" },
	{ id: "0615", state: "CA", statename: "California", party: "D" },
	{ id: "0616", state: "CA", statename: "California", party: "D" },
	{ id: "0617", state: "CA", statename: "California", party: "D" },
	{ id: "0618", state: "CA", statename: "California", party: "D" },
	{ id: "0619", state: "CA", statename: "California", party: "D" },
	{ id: "0620", state: "CA", statename: "California", party: "R" },
	{ id: "0621", state: "CA", statename: "California", party: "D" },
	{ id: "0622", state: "CA", statename: "California", party: "R" },
	{ id: "0623", state: "CA", statename: "California", party: "R" },
	{ id: "0624", state: "CA", statename: "California", party: "D" },
	{ id: "0625", state: "CA", statename: "California", party: "D" },
	{ id: "0626", state: "CA", statename: "California", party: "D" },
	{ id: "0627", state: "CA", statename: "California", party: "R" },
	{ id: "0628", state: "CA", statename: "California", party: "D" },
	{ id: "0629", state: "CA", statename: "California", party: "D" },
	{ id: "0630", state: "CA", statename: "California", party: "D" },
	{ id: "0631", state: "CA", statename: "California", party: "D" },
	{ id: "0632", state: "CA", statename: "California", party: "D" },
	{ id: "0633", state: "CA", statename: "California", party: "D" },
	{ id: "0634", state: "CA", statename: "California", party: "D" },
	{ id: "0635", state: "CA", statename: "California", party: "D" },
	{ id: "0636", state: "CA", statename: "California", party: "D" },
	{ id: "0637", state: "CA", statename: "California", party: "D" },
	{ id: "0638", state: "CA", statename: "California", party: "D" },
	{ id: "0639", state: "CA", statename: "California", party: "D" },
	{ id: "0640", state: "CA", statename: "California", party: "R" },
	{ id: "0641", state: "CA", statename: "California", party: "R" },
	{ id: "0642", state: "CA", statename: "California", party: "N" },
	{ id: "0643", state: "CA", statename: "California", party: "D" },
	{ id: "0644", state: "CA", statename: "California", party: "D" },
	{ id: "0645", state: "CA", statename: "California", party: "R" },
	{ id: "0646", state: "CA", statename: "California", party: "D" },
	{ id: "0647", state: "CA", statename: "California", party: "D" },
	{ id: "0648", state: "CA", statename: "California", party: "R" },
	{ id: "0649", state: "CA", statename: "California", party: "D" },
	{ id: "0650", state: "CA", statename: "California", party: "D" },
	{ id: "0651", state: "CA", statename: "California", party: "D" },
	{ id: "0652", state: "CA", statename: "California", party: "D" },
	{ id: "0801", state: "CO", statename: "Colorado", party: "D" },
	{ id: "0802", state: "CO", statename: "Colorado", party: "D" },
	{ id: "0803", state: "CO", statename: "Colorado", party: "R" },
	{ id: "0804", state: "CO", statename: "Colorado", party: "R" },
	{ id: "0805", state: "CO", statename: "Colorado", party: "R" },
	{ id: "0806", state: "CO", statename: "Colorado", party: "D" },
	{ id: "0807", state: "CO", statename: "Colorado", party: "D" },
	{ id: "0808", state: "CO", statename: "Colorado", party: "N" },
	{ id: "0901", state: "CT", statename: "Connecticut", party: "D" },
	{ id: "0902", state: "CT", statename: "Connecticut", party: "D" },
	{ id: "0903", state: "CT", statename: "Connecticut", party: "D" },
	{ id: "0904", state: "CT", statename: "Connecticut", party: "D" },
	{ id: "0905", state: "CT", statename: "Connecticut", party: "D" },
	{ id: "1000", state: "DE", statename: "Delaware", party: "D" },
	{ id: "1198", state: "DC", statename: "Washington, D.C.", party: "N" },
	{ id: "1201", state: "FL", statename: "Florida", party: "R" },
	{ id: "1202", state: "FL", statename: "Florida", party: "N" },
	{ id: "1203", state: "FL", statename: "Florida", party: "R" },
	{ id: "1204", state: "FL", statename: "Florida", party: "N" },
	{ id: "1205", state: "FL", statename: "Florida", party: "R" },
	{ id: "1206", state: "FL", statename: "Florida", party: "R" },
	{ id: "1207", state: "FL", statename: "Florida", party: "D" },
	{ id: "1208", state: "FL", statename: "Florida", party: "R" },
	{ id: "1209", state: "FL", statename: "Florida", party: "D" },
	{ id: "1210", state: "FL", statename: "Florida", party: "D" },
	{ id: "1211", state: "FL", statename: "Florida", party: "R" },
	{ id: "1212", state: "FL", statename: "Florida", party: "R" },
	{ id: "1213", state: "FL", statename: "Florida", party: "N" },
	{ id: "1214", state: "FL", statename: "Florida", party: "D" },
	{ id: "1215", state: "FL", statename: "Florida", party: "N" },
	{ id: "1216", state: "FL", statename: "Florida", party: "R" },
	{ id: "1217", state: "FL", statename: "Florida", party: "R" },
	{ id: "1218", state: "FL", statename: "Florida", party: "R" },
	{ id: "1219", state: "FL", statename: "Florida", party: "R" },
	{ id: "1220", state: "FL", statename: "Florida", party: "D" },
	{ id: "1221", state: "FL", statename: "Florida", party: "R" },
	{ id: "1222", state: "FL", statename: "Florida", party: "D" },
	{ id: "1223", state: "FL", statename: "Florida", party: "N" },
	{ id: "1224", state: "FL", statename: "Florida", party: "D" },
	{ id: "1225", state: "FL", statename: "Florida", party: "D" },
	{ id: "1226", state: "FL", statename: "Florida", party: "R" },
	{ id: "1227", state: "FL", statename: "Florida", party: "R" },
	{ id: "1228", state: "FL", statename: "Florida", party: "R" },
	{ id: "1301", state: "GA", statename: "Georgia", party: "R" },
	{ id: "1302", state: "GA", statename: "Georgia", party: "D" },
	{ id: "1303", state: "GA", statename: "Georgia", party: "R" },
	{ id: "1304", state: "GA", statename: "Georgia", party: "D" },
	{ id: "1305", state: "GA", statename: "Georgia", party: "D" },
	{ id: "1306", state: "GA", statename: "Georgia", party: "N" },
	{ id: "1307", state: "GA", statename: "Georgia", party: "D" },
	{ id: "1308", state: "GA", statename: "Georgia", party: "R" },
	{ id: "1309", state: "GA", statename: "Georgia", party: "R" },
	{ id: "1310", state: "GA", statename: "Georgia", party: "R" },
	{ id: "1311", state: "GA", statename: "Georgia", party: "R" },
	{ id: "1312", state: "GA", statename: "Georgia", party: "R" },
	{ id: "1313", state: "GA", statename: "Georgia", party: "D" },
	{ id: "1314", state: "GA", statename: "Georgia", party: "R" },
	{ id: "1501", state: "HI", statename: "Hawaii", party: "D" },
	{ id: "1502", state: "HI", statename: "Hawaii", party: "D" },
	{ id: "1901", state: "IA", statename: "Iowa", party: "R" },
	{ id: "1902", state: "IA", statename: "Iowa", party: "R" },
	{ id: "1903", state: "IA", statename: "Iowa", party: "D" },
	{ id: "1904", state: "IA", statename: "Iowa", party: "R" },
	{ id: "1601", state: "ID", statename: "Idaho", party: "R" },
	{ id: "1602", state: "ID", statename: "Idaho", party: "R" },
	{ id: "1701", state: "IL", statename: "Illinois", party: "D" },
	{ id: "1702", state: "IL", statename: "Illinois", party: "D" },
	{ id: "1703", state: "IL", statename: "Illinois", party: "N" },
	{ id: "1704", state: "IL", statename: "Illinois", party: "D" },
	{ id: "1705", state: "IL", statename: "Illinois", party: "D" },
	{ id: "1706", state: "IL", statename: "Illinois", party: "D" },
	{ id: "1707", state: "IL", statename: "Illinois", party: "D" },
	{ id: "1708", state: "IL", statename: "Illinois", party: "D" },
	{ id: "1709", state: "IL", statename: "Illinois", party: "D" },
	{ id: "1710", state: "IL", statename: "Illinois", party: "D" },
	{ id: "1711", state: "IL", statename: "Illinois", party: "D" },
	{ id: "1712", state: "IL", statename: "Illinois", party: "R" },
	{ id: "1713", state: "IL", statename: "Illinois", party: "N" },
	{ id: "1714", state: "IL", statename: "Illinois", party: "D" },
	{ id: "1715", state: "IL", statename: "Illinois", party: "R" },
	{ id: "1716", state: "IL", statename: "Illinois", party: "R" },
	{ id: "1717", state: "IL", statename: "Illinois", party: "D" },
	{ id: "1801", state: "IN", statename: "Indiana", party: "D" },
	{ id: "1802", state: "IN", statename: "Indiana", party: "N" },
	{ id: "1803", state: "IN", statename: "Indiana", party: "R" },
	{ id: "1804", state: "IN", statename: "Indiana", party: "R" },
	{ id: "1805", state: "IN", statename: "Indiana", party: "R" },
	{ id: "1806", state: "IN", statename: "Indiana", party: "R" },
	{ id: "1807", state: "IN", statename: "Indiana", party: "D" },
	{ id: "1808", state: "IN", statename: "Indiana", party: "R" },
	{ id: "1809", state: "IN", statename: "Indiana", party: "R" },
	{ id: "2001", state: "KS", statename: "Kansas", party: "R" },
	{ id: "2002", state: "KS", statename: "Kansas", party: "R" },
	{ id: "2003", state: "KS", statename: "Kansas", party: "D" },
	{ id: "2004", state: "KS", statename: "Kansas", party: "R" },
	{ id: "2101", state: "KY", statename: "Kentucky", party: "R" },
	{ id: "2102", state: "KY", statename: "Kentucky", party: "R" },
	{ id: "2103", state: "KY", statename: "Kentucky", party: "D" },
	{ id: "2104", state: "KY", statename: "Kentucky", party: "R" },
	{ id: "2105", state: "KY", statename: "Kentucky", party: "R" },
	{ id: "2106", state: "KY", statename: "Kentucky", party: "R" },
	{ id: "2201", state: "LA", statename: "Louisiana", party: "R" },
	{ id: "2202", state: "LA", statename: "Louisiana", party: "D" },
	{ id: "2203", state: "LA", statename: "Louisiana", party: "R" },
	{ id: "2204", state: "LA", statename: "Louisiana", party: "R" },
	{ id: "2205", state: "LA", statename: "Louisiana", party: "R" },
	{ id: "2206", state: "LA", statename: "Louisiana", party: "R" },
	{ id: "2501", state: "MA", statename: "Massachusetts", party: "D" },
	{ id: "2502", state: "MA", statename: "Massachusetts", party: "D" },
	{ id: "2503", state: "MA", statename: "Massachusetts", party: "D" },
	{ id: "2504", state: "MA", statename: "Massachusetts", party: "D" },
	{ id: "2505", state: "MA", statename: "Massachusetts", party: "D" },
	{ id: "2506", state: "MA", statename: "Massachusetts", party: "D" },
	{ id: "2507", state: "MA", statename: "Massachusetts", party: "D" },
	{ id: "2508", state: "MA", statename: "Massachusetts", party: "D" },
	{ id: "2509", state: "MA", statename: "Massachusetts", party: "D" },
	{ id: "2401", state: "MD", statename: "Maryland", party: "R" },
	{ id: "2402", state: "MD", statename: "Maryland", party: "D" },
	{ id: "2403", state: "MD", statename: "Maryland", party: "D" },
	{ id: "2404", state: "MD", statename: "Maryland", party: "D" },
	{ id: "2405", state: "MD", statename: "Maryland", party: "D" },
	{ id: "2406", state: "MD", statename: "Maryland", party: "D" },
	{ id: "2407", state: "MD", statename: "Maryland", party: "D" },
	{ id: "2408", state: "MD", statename: "Maryland", party: "D" },
	{ id: "2301", state: "ME", statename: "Maine", party: "D" },
	{ id: "2302", state: "ME", statename: "Maine", party: "D" },
	{ id: "2601", state: "MI", statename: "Michigan", party: "R" },
	{ id: "2602", state: "MI", statename: "Michigan", party: "R" },
	{ id: "2603", state: "MI", statename: "Michigan", party: "R" },
	{ id: "2604", state: "MI", statename: "Michigan", party: "R" },
	{ id: "2605", state: "MI", statename: "Michigan", party: "R" },
	{ id: "2606", state: "MI", statename: "Michigan", party: "D" },
	{ id: "2607", state: "MI", statename: "Michigan", party: "D" },
	{ id: "2608", state: "MI", statename: "Michigan", party: "D" },
	{ id: "2609", state: "MI", statename: "Michigan", party: "R" },
	{ id: "2610", state: "MI", statename: "Michigan", party: "N" },
	{ id: "2611", state: "MI", statename: "Michigan", party: "D" },
	{ id: "2612", state: "MI", statename: "Michigan", party: "D" },
	{ id: "2613", state: "MI", statename: "Michigan", party: "D" },
	{ id: "2701", state: "MN", statename: "Minnesota", party: "R" },
	{ id: "2702", state: "MN", statename: "Minnesota", party: "D" },
	{ id: "2703", state: "MN", statename: "Minnesota", party: "D" },
	{ id: "2704", state: "MN", statename: "Minnesota", party: "D" },
	{ id: "2705", state: "MN", statename: "Minnesota", party: "D" },
	{ id: "2706", state: "MN", statename: "Minnesota", party: "R" },
	{ id: "2707", state: "MN", statename: "Minnesota", party: "R" },
	{ id: "2708", state: "MN", statename: "Minnesota", party: "R" },
	{ id: "2901", state: "MO", statename: "Missouri", party: "D" },
	{ id: "2902", state: "MO", statename: "Missouri", party: "R" },
	{ id: "2903", state: "MO", statename: "Missouri", party: "R" },
	{ id: "2904", state: "MO", statename: "Missouri", party: "R" },
	{ id: "2905", state: "MO", statename: "Missouri", party: "D" },
	{ id: "2906", state: "MO", statename: "Missouri", party: "R" },
	{ id: "2907", state: "MO", statename: "Missouri", party: "R" },
	{ id: "2908", state: "MO", statename: "Missouri", party: "R" },
	{ id: "2801", state: "MS", statename: "Mississippi", party: "R" },
	{ id: "2802", state: "MS", statename: "Mississippi", party: "D" },
	{ id: "2803", state: "MS", statename: "Mississippi", party: "R" },
	{ id: "2804", state: "MS", statename: "Mississippi", party: "R" },
	{ id: "3001", state: "MT", statename: "Montana", party: "N" },
	{ id: "3002", state: "MT", statename: "Montana", party: "R" },
	{ id: "3701", state: "NC", statename: "North Carolina", party: "D" },
	{ id: "3702", state: "NC", statename: "North Carolina", party: "D" },
	{ id: "3703", state: "NC", statename: "North Carolina", party: "R" },
	{ id: "3704", state: "NC", statename: "North Carolina", party: "D" },
	{ id: "3705", state: "NC", statename: "North Carolina", party: "R" },
	{ id: "3706", state: "NC", statename: "North Carolina", party: "D" },
	{ id: "3707", state: "NC", statename: "North Carolina", party: "R" },
	{ id: "3708", state: "NC", statename: "North Carolina", party: "R" },
	{ id: "3709", state: "NC", statename: "North Carolina", party: "R" },
	{ id: "3710", state: "NC", statename: "North Carolina", party: "R" },
	{ id: "3711", state: "NC", statename: "North Carolina", party: "R" },
	{ id: "3712", state: "NC", statename: "North Carolina", party: "D" },
	{ id: "3713", state: "NC", statename: "North Carolina", party: "N" },
	{ id: "3714", state: "NC", statename: "North Carolina", party: "N" },
	{ id: "3800", state: "ND", statename: "North Dakota", party: "R" },
	{ id: "3101", state: "NE", statename: "Nebraska", party: "R" },
	{ id: "3102", state: "NE", statename: "Nebraska", party: "R" },
	{ id: "3103", state: "NE", statename: "Nebraska", party: "R" },
	{ id: "3301", state: "NH", statename: "New Hampshire", party: "D" },
	{ id: "3302", state: "NH", statename: "New Hampshire", party: "D" },
	{ id: "3401", state: "NJ", statename: "New Jersey", party: "D" },
	{ id: "3402", state: "NJ", statename: "New Jersey", party: "R" },
	{ id: "3403", state: "NJ", statename: "New Jersey", party: "D" },
	{ id: "3404", state: "NJ", statename: "New Jersey", party: "R" },
	{ id: "3405", state: "NJ", statename: "New Jersey", party: "D" },
	{ id: "3406", state: "NJ", statename: "New Jersey", party: "D" },
	{ id: "3407", state: "NJ", statename: "New Jersey", party: "D" },
	{ id: "3408", state: "NJ", statename: "New Jersey", party: "D" },
	{ id: "3409", state: "NJ", statename: "New Jersey", party: "D" },
	{ id: "3410", state: "NJ", statename: "New Jersey", party: "D" },
	{ id: "3411", state: "NJ", statename: "New Jersey", party: "D" },
	{ id: "3412", state: "NJ", statename: "New Jersey", party: "D" },
	{ id: "3501", state: "NM", statename: "New Mexico", party: "D" },
	{ id: "3502", state: "NM", statename: "New Mexico", party: "R" },
	{ id: "3503", state: "NM", statename: "New Mexico", party: "D" },
	{ id: "3201", state: "NV", statename: "Nevada", party: "D" },
	{ id: "3202", state: "NV", statename: "Nevada", party: "R" },
	{ id: "3203", state: "NV", statename: "Nevada", party: "D" },
	{ id: "3204", state: "NV", statename: "Nevada", party: "D" },
	{ id: "3601", state: "NY", statename: "New York", party: "R" },
	{ id: "3602", state: "NY", statename: "New York", party: "R" },
	{ id: "3603", state: "NY", statename: "New York", party: "D" },
	{ id: "3604", state: "NY", statename: "New York", party: "D" },
	{ id: "3605", state: "NY", statename: "New York", party: "D" },
	{ id: "3606", state: "NY", statename: "New York", party: "D" },
	{ id: "3607", state: "NY", statename: "New York", party: "D" },
	{ id: "3608", state: "NY", statename: "New York", party: "D" },
	{ id: "3609", state: "NY", statename: "New York", party: "D" },
	{ id: "3610", state: "NY", statename: "New York", party: "D" },
	{ id: "3611", state: "NY", statename: "New York", party: "R" },
	{ id: "3612", state: "NY", statename: "New York", party: "D" },
	{ id: "3613", state: "NY", statename: "New York", party: "D" },
	{ id: "3614", state: "NY", statename: "New York", party: "D" },
	{ id: "3615", state: "NY", statename: "New York", party: "D" },
	{ id: "3616", state: "NY", statename: "New York", party: "D" },
	{ id: "3617", state: "NY", statename: "New York", party: "D" },
	{ id: "3618", state: "NY", statename: "New York", party: "D" },
	{ id: "3619", state: "NY", statename: "New York", party: "N" },
	{ id: "3620", state: "NY", statename: "New York", party: "D" },
	{ id: "3621", state: "NY", statename: "New York", party: "R" },
	{ id: "3622", state: "NY", statename: "New York", party: "R" },
	{ id: "3623", state: "NY", statename: "New York", party: "R" },
	{ id: "3624", state: "NY", statename: "New York", party: "R" },
	{ id: "3625", state: "NY", statename: "New York", party: "D" },
	{ id: "3626", state: "NY", statename: "New York", party: "D" },
	{ id: "3901", state: "OH", statename: "Ohio", party: "R" },
	{ id: "3902", state: "OH", statename: "Ohio", party: "R" },
	{ id: "3903", state: "OH", statename: "Ohio", party: "D" },
	{ id: "3904", state: "OH", statename: "Ohio", party: "R" },
	{ id: "3905", state: "OH", statename: "Ohio", party: "R" },
	{ id: "3906", state: "OH", statename: "Ohio", party: "R" },
	{ id: "3907", state: "OH", statename: "Ohio", party: "R" },
	{ id: "3908", state: "OH", statename: "Ohio", party: "R" },
	{ id: "3909", state: "OH", statename: "Ohio", party: "D" },
	{ id: "3910", state: "OH", statename: "Ohio", party: "R" },
	{ id: "3911", state: "OH", statename: "Ohio", party: "D" },
	{ id: "3912", state: "OH", statename: "Ohio", party: "R" },
	{ id: "3913", state: "OH", statename: "Ohio", party: "R" },
	{ id: "3914", state: "OH", statename: "Ohio", party: "R" },
	{ id: "3915", state: "OH", statename: "Ohio", party: "R" },
	{ id: "4001", state: "OK", statename: "Oklahoma", party: "R" },
	{ id: "4002", state: "OK", statename: "Oklahoma", party: "R" },
	{ id: "4003", state: "OK", statename: "Oklahoma", party: "R" },
	{ id: "4004", state: "OK", statename: "Oklahoma", party: "R" },
	{ id: "4005", state: "OK", statename: "Oklahoma", party: "R" },
	{ id: "4101", state: "OR", statename: "Oregon", party: "D" },
	{ id: "4102", state: "OR", statename: "Oregon", party: "R" },
	{ id: "4103", state: "OR", statename: "Oregon", party: "D" },
	{ id: "4104", state: "OR", statename: "Oregon", party: "D" },
	{ id: "4105", state: "OR", statename: "Oregon", party: "D" },
	{ id: "4106", state: "OR", statename: "Oregon", party: "N" },
	{ id: "4201", state: "PA", statename: "Pennsylvania", party: "R" },
	{ id: "4202", state: "PA", statename: "Pennsylvania", party: "D" },
	{ id: "4203", state: "PA", statename: "Pennsylvania", party: "D" },
	{ id: "4204", state: "PA", statename: "Pennsylvania", party: "D" },
	{ id: "4205", state: "PA", statename: "Pennsylvania", party: "D" },
	{ id: "4206", state: "PA", statename: "Pennsylvania", party: "D" },
	{ id: "4207", state: "PA", statename: "Pennsylvania", party: "D" },
	{ id: "4208", state: "PA", statename: "Pennsylvania", party: "D" },
	{ id: "4209", state: "PA", statename: "Pennsylvania", party: "R" },
	{ id: "4210", state: "PA", statename: "Pennsylvania", party: "R" },
	{ id: "4211", state: "PA", statename: "Pennsylvania", party: "R" },
	{ id: "4212", state: "PA", statename: "Pennsylvania", party: "D" },
	{ id: "4213", state: "PA", statename: "Pennsylvania", party: "R" },
	{ id: "4214", state: "PA", statename: "Pennsylvania", party: "R" },
	{ id: "4215", state: "PA", statename: "Pennsylvania", party: "R" },
	{ id: "4216", state: "PA", statename: "Pennsylvania", party: "R" },
	{ id: "4217", state: "PA", statename: "Pennsylvania", party: "D" },
	{ id: "4401", state: "RI", statename: "Rhode Island", party: "D" },
	{ id: "4402", state: "RI", statename: "Rhode Island", party: "D" },
	{ id: "4501", state: "SC", statename: "South Carolina", party: "R" },
	{ id: "4502", state: "SC", statename: "South Carolina", party: "R" },
	{ id: "4503", state: "SC", statename: "South Carolina", party: "R" },
	{ id: "4504", state: "SC", statename: "South Carolina", party: "R" },
	{ id: "4505", state: "SC", statename: "South Carolina", party: "R" },
	{ id: "4506", state: "SC", statename: "South Carolina", party: "D" },
	{ id: "4507", state: "SC", statename: "South Carolina", party: "R" },
	{ id: "4600", state: "SD", statename: "South Dakota", party: "R" },
	{ id: "4701", state: "TN", statename: "Tennessee", party: "R" },
	{ id: "4702", state: "TN", statename: "Tennessee", party: "R" },
	{ id: "4703", state: "TN", statename: "Tennessee", party: "R" },
	{ id: "4704", state: "TN", statename: "Tennessee", party: "R" },
	{ id: "4705", state: "TN", statename: "Tennessee", party: "D" },
	{ id: "4706", state: "TN", statename: "Tennessee", party: "R" },
	{ id: "4707", state: "TN", statename: "Tennessee", party: "R" },
	{ id: "4708", state: "TN", statename: "Tennessee", party: "R" },
	{ id: "4709", state: "TN", statename: "Tennessee", party: "D" },
	{ id: "4801", state: "TX", statename: "Texas", party: "R" },
	{ id: "4802", state: "TX", statename: "Texas", party: "R" },
	{ id: "4803", state: "TX", statename: "Texas", party: "R" },
	{ id: "4804", state: "TX", statename: "Texas", party: "R" },
	{ id: "4805", state: "TX", statename: "Texas", party: "R" },
	{ id: "4806", state: "TX", statename: "Texas", party: "R" },
	{ id: "4807", state: "TX", statename: "Texas", party: "D" },
	{ id: "4808", state: "TX", statename: "Texas", party: "R" },
	{ id: "4809", state: "TX", statename: "Texas", party: "D" },
	{ id: "4810", state: "TX", statename: "Texas", party: "R" },
	{ id: "4811", state: "TX", statename: "Texas", party: "R" },
	{ id: "4812", state: "TX", statename: "Texas", party: "R" },
	{ id: "4813", state: "TX", statename: "Texas", party: "R" },
	{ id: "4814", state: "TX", statename: "Texas", party: "R" },
	{ id: "4815", state: "TX", statename: "Texas", party: "N" },
	{ id: "4816", state: "TX", statename: "Texas", party: "D" },
	{ id: "4817", state: "TX", statename: "Texas", party: "R" },
	{ id: "4818", state: "TX", statename: "Texas", party: "D" },
	{ id: "4819", state: "TX", statename: "Texas", party: "R" },
	{ id: "4820", state: "TX", statename: "Texas", party: "D" },
	{ id: "4821", state: "TX", statename: "Texas", party: "R" },
	{ id: "4822", state: "TX", statename: "Texas", party: "R" },
	{ id: "4823", state: "TX", statename: "Texas", party: "R" },
	{ id: "4824", state: "TX", statename: "Texas", party: "R" },
	{ id: "4825", state: "TX", statename: "Texas", party: "R" },
	{ id: "4826", state: "TX", statename: "Texas", party: "R" },
	{ id: "4827", state: "TX", statename: "Texas", party: "R" },
	{ id: "4828", state: "TX", statename: "Texas", party: "D" },
	{ id: "4829", state: "TX", statename: "Texas", party: "D" },
	{ id: "4830", state: "TX", statename: "Texas", party: "D" },
	{ id: "4831", state: "TX", statename: "Texas", party: "R" },
	{ id: "4832", state: "TX", statename: "Texas", party: "D" },
	{ id: "4833", state: "TX", statename: "Texas", party: "D" },
	{ id: "4834", state: "TX", statename: "Texas", party: "N" },
	{ id: "4835", state: "TX", statename: "Texas", party: "N" },
	{ id: "4836", state: "TX", statename: "Texas", party: "R" },
	{ id: "4837", state: "TX", statename: "Texas", party: "D" },
	{ id: "4838", state: "TX", statename: "Texas", party: "N" },
	{ id: "4901", state: "UT", statename: "Utah", party: "R" },
	{ id: "4902", state: "UT", statename: "Utah", party: "R" },
	{ id: "4903", state: "UT", statename: "Utah", party: "R" },
	{ id: "4904", state: "UT", statename: "Utah", party: "R" },
	{ id: "5101", state: "VA", statename: "Virginia", party: "R" },
	{ id: "5102", state: "VA", statename: "Virginia", party: "D" },
	{ id: "5103", state: "VA", statename: "Virginia", party: "D" },
	{ id: "5104", state: "VA", statename: "Virginia", party: "D" },
	{ id: "5105", state: "VA", statename: "Virginia", party: "R" },
	{ id: "5106", state: "VA", statename: "Virginia", party: "R" },
	{ id: "5107", state: "VA", statename: "Virginia", party: "D" },
	{ id: "5108", state: "VA", statename: "Virginia", party: "D" },
	{ id: "5109", state: "VA", statename: "Virginia", party: "R" },
	{ id: "5110", state: "VA", statename: "Virginia", party: "D" },
	{ id: "5111", state: "VA", statename: "Virginia", party: "D" },
	{ id: "5000", state: "VT", statename: "Vermont", party: "D" },
	{ id: "5301", state: "WA", statename: "Washington", party: "D" },
	{ id: "5302", state: "WA", statename: "Washington", party: "D" },
	{ id: "5303", state: "WA", statename: "Washington", party: "R" },
	{ id: "5304", state: "WA", statename: "Washington", party: "R" },
	{ id: "5305", state: "WA", statename: "Washington", party: "R" },
	{ id: "5306", state: "WA", statename: "Washington", party: "D" },
	{ id: "5307", state: "WA", statename: "Washington", party: "D" },
	{ id: "5308", state: "WA", statename: "Washington", party: "D" },
	{ id: "5309", state: "WA", statename: "Washington", party: "D" },
	{ id: "5310", state: "WA", statename: "Washington", party: "D" },
	{ id: "5501", state: "WI", statename: "Wisconsin", party: "R" },
	{ id: "5502", state: "WI", statename: "Wisconsin", party: "D" },
	{ id: "5503", state: "WI", statename: "Wisconsin", party: "D" },
	{ id: "5504", state: "WI", statename: "Wisconsin", party: "D" },
	{ id: "5505", state: "WI", statename: "Wisconsin", party: "R" },
	{ id: "5506", state: "WI", statename: "Wisconsin", party: "R" },
	{ id: "5507", state: "WI", statename: "Wisconsin", party: "R" },
	{ id: "5508", state: "WI", statename: "Wisconsin", party: "R" },
	{ id: "5401", state: "WV", statename: "West Virginia", party: "R" },
	{ id: "5402", state: "WV", statename: "West Virginia", party: "R" },
	{ id: "5600", state: "WY", statename: "Wyoming", party: "R" }
];

// Populate colors
for(var i = 0; i < data.length; i++) {
  data[i].polygonSettings = {
    fill: colors[data[i].party]
  }
}

// Create root and chart
var root = am5.Root.new("chartdiv"); 

// Set themes
root.setThemes([
  am5themes_Animated.new(root)
]);

var chart = root.container.children.push(
  am5map.MapChart.new(root, {
    //panX: "rotateX",
    projection: am5map.geoAlbersUsa()
  })
);

// Create polygon series
var polygonSeries = chart.series.push(
  am5map.MapPolygonSeries.new(root, {
    geoJSON: am5geodata_region_usa_congressional2022_usaCongressionalLow
  })
);


polygonSeries.mapPolygons.template.setAll({
  tooltipText: "[bold]{STATENAME} ({party})[/]\n{name}",
  templateField: "polygonSettings",
  fillOpacity: 0.9
});

polygonSeries.mapPolygons.template.states.create("hover", {
  fillOpacity: 1
});

polygonSeries.data.setAll(data);

// Legend
var legend = chart.children.push(am5.Legend.new(root, {
  nameField: "name",
  fillField: "color",
  strokeField: "color",
  useDefaultMarker: true,
  centerX: am5.p100,
  maxWidth: 100,
  x: am5.p100,
  centerY: am5.p100,
  y: am5.p100,
  dx: -20,
  dy: -20,
  background: am5.RoundedRectangle.new(root, {
    fill: am5.color(0xffffff),
    fillOpacity: 0.3
  })
}));

legend.data.setAll([{
  name: "Democrats",
  color: colors.D
}, {
  name: "Republicans",
  color: colors.R
}, {
  name: "Neutral",
  color: colors.N
}]);